-- iMavy Analytics Realtime Setup
-- Execute no SQL Editor do Supabase.

create table if not exists public.interacoes_texto (
  id bigint generated by default as identity primary key,
  message_id text not null unique,
  nome text not null,
  grupo text not null,
  grupo_id text,
  sender_id text,
  texto text,
  data date not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_interacoes_texto_data on public.interacoes_texto (data);
create index if not exists idx_interacoes_texto_grupo on public.interacoes_texto (grupo);
create index if not exists idx_interacoes_texto_created_at on public.interacoes_texto (created_at desc);

alter table public.interacoes_texto enable row level security;

-- Permitir leitura para chave anon (dashboard frontend)
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'interacoes_texto' and policyname = 'interacoes_texto_select_anon'
  ) then
    create policy interacoes_texto_select_anon
      on public.interacoes_texto
      for select
      to anon
      using (true);
  end if;
end $$;

-- Permitir insert/upsert para chave anon (bot)
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'interacoes_texto' and policyname = 'interacoes_texto_insert_anon'
  ) then
    create policy interacoes_texto_insert_anon
      on public.interacoes_texto
      for insert
      to anon
      with check (true);
  end if;
end $$;

-- Habilitar realtime na tabela (idempotente)
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'interacoes_texto'
  ) then
    alter publication supabase_realtime add table public.interacoes_texto;
  end if;
end $$;
